// Uganda district names, exactly as seeded into `public.districts`.
//
// WHY THIS EXISTS: `approve_access_request` resolves the district NAME a
// requester typed back to a `districts.id` (`lower(name) = lower(...)`). A value
// that isn't in this list resolves to NULL — which, before migration 0090,
// silently provisioned an employer with no geography, and after 0090 makes the
// request un-approvable. So the request form constrains input to these names.
//
// Generated from `src/data/mockGeo.js` (the same source the seed reads):
//   Object.values(DISTRICTS).map((d) => d.name).sort()
// Committed as a literal rather than imported, because CLAUDE.md §4.1 forbids
// components importing `src/data/*`. Regenerate if the district set changes.
export const DISTRICT_NAMES = [
  'Abim',
  'Adjumani',
  'Agago',
  'Alebtong',
  'Amolatar',
  'Amudat',
  'Amuria',
  'Amuru',
  'Apac',
  'Arua',
  'Budaka',
  'Bududa',
  'Bugiri',
  'Bugweri',
  'Buhweju',
  'Buikwe',
  'Bukedea',
  'Bukomansimbi',
  'Bukwo',
  'Bulambuli',
  'Buliisa',
  'Bundibugyo',
  'Bunyangabu',
  'Bushenyi',
  'Busia',
  'Butaleja',
  'Butambala',
  'Butebo',
  'Buvuma',
  'Buyende',
  'Dokolo',
  'Gomba',
  'Gulu',
  'Hoima',
  'Ibanda',
  'Iganga',
  'Isingiro',
  'Jinja',
  'Kaabong',
  'Kabale',
  'Kabarole',
  'Kaberamaido',
  'Kagadi',
  'Kakumiro',
  'Kalaki',
  'Kalangala',
  'Kaliro',
  'Kalungu',
  'Kampala',
  'Kamuli',
  'Kamwenge',
  'Kanungu',
  'Kapchorwa',
  'Kapelebyong',
  'Karenga',
  'Kasese',
  'Kassanda',
  'Katakwi',
  'Kayunga',
  'Kazo',
  'Kibaale',
  'Kiboga',
  'Kibuku',
  'Kikuube',
  'Kiruhura',
  'Kiryandongo',
  'Kisoro',
  'Kitagwenda',
  'Kitgum',
  'Koboko',
  'Kole',
  'Kotido',
  'Kumi',
  'Kwania',
  'Kween',
  'Kyankwanzi',
  'Kyegegwa',
  'Kyenjojo',
  'Kyotera',
  'Lamwo',
  'Lira',
  'Luuka',
  'Luwero',
  'Lwengo',
  'Lyantonde',
  'Madi Okollo',
  'Manafwa',
  'Maracha',
  'Masaka',
  'Masindi',
  'Mayuge',
  'Mbale',
  'Mbarara',
  'Mitooma',
  'Mityana',
  'Moroto',
  'Moyo',
  'Mpigi',
  'Mubende',
  'Mukono',
  'Nabilatuk',
  'Nakapiripirit',
  'Nakaseke',
  'Nakasongola',
  'Namayingo',
  'Namisindwa',
  'Namutumba',
  'Napak',
  'Nebbi',
  'Ngora',
  'Ntoroko',
  'Ntungamo',
  'Nwoya',
  'Obongi',
  'Omoro',
  'Otuke',
  'Oyam',
  'Pader',
  'Pakwach',
  'Pallisa',
  'Rakai',
  'Rubanda',
  'Rubirizi',
  'Rukiga',
  'Rukungiri',
  'Rwampara',
  'Serere',
  'Sheema',
  'Sironko',
  'Soroti',
  'Ssembabule',
  'Terego',
  'Tororo',
  'Wakiso',
  'Yumbe',
  'Zombo',];

/** Case-insensitive membership test used by the request-access validator. */
export function isKnownDistrict(name) {
  const needle = String(name ?? '').trim().toLowerCase();
  if (!needle) return false;
  return DISTRICT_NAMES.some((d) => d.toLowerCase() === needle);
}
