-- =============================================================================
-- Universal Pensions Uganda — 0104: NAV pricing, part 2 of 3 (money + admin RPCs)
-- =============================================================================
-- WHY
--   0103 built the register and the price helpers but changed no behaviour.
--   This file makes the NAV actually price money, and gives the admin the RPCs
--   behind the new "Unit price" page. 0105 then backfills history.
--
-- HOW THE TWO MONEY FUNCTIONS WERE PRODUCED — READ BEFORE EDITING
--   trg_transactions_contribution and request_withdrawal below were NOT retyped.
--   They were generated by transforming their CURRENT LIVE definitions
--   (pg_get_functiondef) with substitutions that each ASSERT A UNIQUE MATCH, then
--   diffed against the live text to prove nothing but the intended lines moved.
--   This is the 0072/0089/0102 discipline, and it exists because retyping a
--   ~200-line body is exactly how 0095 silently dropped 0090's work.
--   12 substitutions, all matched exactly once:
--     contribution — declare · assign-from-register · insert-cols · insert-values
--                    · on-conflict · sweep-redemption · stale-invariant-comment
--     withdrawal   — declare · assign-from-register · redeem-and-rebase
--                    · resync-after-clawback · stale-invariant-comment
--   Both keep their ORIGINAL security context (SECURITY DEFINER + pinned
--   search_path) and request_withdrawal keeps its exact 7-argument signature,
--   which 0072's REVOKE/GRANT names.
--
-- THE ACCOUNTING RULES ENCODED HERE
--   * A contribution buys units at nav_for_date(NEW.date) — its OWN date, so a
--     back-dated employer run prices at that period's NAV, not today's.
--   * A withdrawal or a save-to-cover sweep redeems LEAST(amount/NAV, units).
--     The cap is not defensive noise: 1,024 of 5,060 members carry a ledger that
--     goes negative (the seed books its opening reconciliation as a NEGATIVE
--     withdrawal dated at registration, chronologically first). Without the cap
--     those members get negative units and a NaN cost basis.
--   * Cost basis falls by the UNIT fraction, not the value fraction:
--     invested × (1 − redeemed/held). Because the fraction of units removed
--     equals the fraction of basis removed, growth% is INVARIANT to withdrawals.
--     Reducing by simple net cash-in instead produces −233% / +98% outliers —
--     measured against the live ledger, not hypothesised.
--   * Bucket units are DERIVED by _resync_bucket_units (0103) after every cash
--     mutation, never hand-maintained, with emergency as the COMPLEMENT so
--     retirement_units + emergency_units == units exactly.
--
-- DELIBERATELY NOT TOUCHED
--   * trg_transactions_withdrawal — debits bucket BALANCES by withdrawn cash and
--     never touches units. request_withdrawal redeems units at the same NAV in
--     the same statement, so the two cannot drift. No change needed.
--   * _insert_subscriber_chain — SECURITY INVOKER, MUST STAY INVOKER.
--   * submit_employer_contribution_run (0102) — writes only `transactions`; its
--     legs are priced by the trigger for free.
--   * create_subscriber_from_employer_invite / _onboard — 0103's NOT NULL
--     DEFAULT 0 columns mean their explicit INSERT column lists still work.
--
-- SCHEMA FACTS VERIFIED against live before writing (2026-08-08)
--   * trg_subscribers_enforce_editable_cols is SECURITY INVOKER and opens with
--     `IF v_role IS DISTINCT FROM 'subscriber' THEN RETURN NEW; END IF;` — so an
--     ADMIN jwt may write current_unit_value / unit_value_as_of, which is what
--     publish_nav_snapshot relies on. It needs no re-emission.
--   * guard_mass_subscriber_detach (statement-level, AFTER UPDATE) counts only
--     rows where agent_id or employer_id goes NOT NULL -> NULL. Stamping the unit
--     price on all 5,064 subscribers does not trip it.
--   * v_reconciliation_exceptions.split_mismatch fires at >1 UGX, hence the
--     complement rule in the revaluation.
--
-- Applied to the live Singapore DB 2026-08-08.
-- =============================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) trg_transactions_contribution — priced from the register
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.trg_transactions_contribution()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_unit_price       NUMERIC;   -- 0104: the fund NAV, assigned in BEGIN
  v_retirement_share NUMERIC;
  v_emergency_share  NUMERIC;
  v_agent_id         TEXT;
  v_branch_id        TEXT;
  v_subscriber_name  TEXT;
  v_commission_rate  NUMERIC;
  v_new_commission_id TEXT;
  -- 0072 additions (save-to-cover accrual/sweep + lazy indexation):
  v_sched            public.contribution_schedules%ROWTYPE;
  v_target           NUMERIC;
  v_new_accrued      NUMERIC;
  v_emg_bal          NUMERIC;
BEGIN
  -- 0104: price this contribution at the fund NAV in force on its OWN date, so
  -- a back-dated employer run prices at that period's NAV, not today's. This
  -- cannot be a DECLARE initialiser — that context cannot reference NEW.
  v_unit_price := public.nav_for_date(COALESCE(NEW.date::date, CURRENT_DATE));

  -- (b) Bucket split ---------------------------------------------------------
  IF NEW.split_retirement IS NOT NULL AND NEW.split_emergency IS NOT NULL THEN
    v_retirement_share := NEW.split_retirement;
    v_emergency_share  := NEW.split_emergency;
  ELSE
    v_retirement_share := ROUND(NEW.amount * 0.80);
    v_emergency_share  := NEW.amount - v_retirement_share;  -- avoids penny drift
  END IF;

  -- (a) Balance update -------------------------------------------------------
  INSERT INTO public.subscriber_balances (
    subscriber_id,
    retirement_balance,
    emergency_balance,
    total_balance,
    units,
    invested,
    nav_as_of,
    updated_at
  ) VALUES (
    NEW.subscriber_id,
    v_retirement_share,
    v_emergency_share,
    NEW.amount,
    NEW.amount / v_unit_price,
    NEW.amount,
    CURRENT_DATE,
    now()
  )
  ON CONFLICT (subscriber_id) DO UPDATE SET
    retirement_balance = public.subscriber_balances.retirement_balance + EXCLUDED.retirement_balance,
    emergency_balance  = public.subscriber_balances.emergency_balance  + EXCLUDED.emergency_balance,
    total_balance      = public.subscriber_balances.total_balance      + EXCLUDED.total_balance,
    units              = public.subscriber_balances.units              + EXCLUDED.units,
    invested           = public.subscriber_balances.invested           + EXCLUDED.invested,
    nav_as_of          = EXCLUDED.nav_as_of,
    updated_at         = now();

  -- 0104: bucket units are DERIVED, never hand-maintained. See _resync_bucket_units.
  PERFORM public._resync_bucket_units(NEW.subscriber_id);

  -- ── 0072: save-to-cover accrual + lazy renewal + lazy indexation ──────────
  -- [M4] Own-money legs only — the employer co-contribution (source='employer')
  -- and the employer group insurance leg never accrue toward a self policy.
  IF NEW.source = 'own' THEN
    SELECT * INTO v_sched FROM public.contribution_schedules
      WHERE subscriber_id = NEW.subscriber_id FOR UPDATE;   -- lock the 1:1 row

    IF v_sched.insurance_funding_mode = 'save_to_cover' THEN

      -- [M1] LAZY RENEWAL (no pg_cron): any active SELF policy whose renewal_date
      -- has passed flips back to 'building' so it re-accrues. Flip BOTH tables.
      UPDATE public.insurance_policies
         SET status = 'building'
       WHERE subscriber_id = NEW.subscriber_id AND funded_by = 'self'
         AND status = 'active' AND renewal_date IS NOT NULL AND now() >= renewal_date;
      UPDATE public.subscriber_insurance_products
         SET status = 'building', updated_at = now()
       WHERE subscriber_id = NEW.subscriber_id AND funded_by = 'self'
         AND status = 'active' AND renewal_date IS NOT NULL AND now() >= renewal_date;

      -- [M8] Recompute target = SUM(annual premium of every NON-active self
      -- policy). annual = premium_monthly * 12 (the app's single annual anchor).
      SELECT COALESCE(SUM(premium_monthly * 12), 0) INTO v_target
        FROM ( SELECT premium_monthly FROM public.insurance_policies
                 WHERE subscriber_id = NEW.subscriber_id AND funded_by = 'self' AND status <> 'active'
               UNION ALL
               SELECT premium_monthly FROM public.subscriber_insurance_products
                 WHERE subscriber_id = NEW.subscriber_id AND funded_by = 'self' AND status <> 'active' ) q;

      IF v_target > 0 THEN
        -- Accrue the ASSIGNED SHARE of this contribution's emergency slice toward
        -- cover (insurance_savings_pct; the rest stays liquid/withdrawable), CAPPED
        -- at target ([L1] any excess simply stays in emergency_balance — never lost).
        v_new_accrued := LEAST(
          v_target,
          v_sched.insurance_premium_accrued
            + v_emergency_share * (COALESCE(v_sched.insurance_savings_pct, 100) / 100.0));

        -- Read the emergency balance we just credited above.
        SELECT emergency_balance INTO v_emg_bal
          FROM public.subscriber_balances WHERE subscriber_id = NEW.subscriber_id;

        -- [H3] SWEEP GUARD: accrued reached target AND the money is actually there.
        IF v_new_accrued >= v_target AND v_emg_bal >= v_target THEN
          -- Debit buckets by the ANNUAL target, and units by target/NAV ([H1]) —
          -- NEVER by target — so units × NAV == total_balance stays EXACT
          -- (units are credited un-rounded above; do not round here).
          -- 0104: redeem at the day's NAV, capped at units actually held, and
          -- drop the SAME FRACTION of cost basis as of units (average-cost), so
          -- paying an annual premium out of savings is not read as a loss.
          -- Every SET right-hand side reads the PRE-UPDATE row, so `units` here
          -- is the holding before this redemption.
          UPDATE public.subscriber_balances
             SET emergency_balance = emergency_balance - v_target,
                 total_balance     = total_balance     - v_target,
                 units             = units - LEAST(v_target / v_unit_price, units),
                 invested          = CASE WHEN units > 0
                                       THEN GREATEST(0, invested * (1 - LEAST(v_target / v_unit_price, units) / units))
                                       ELSE 0 END,
                 nav_as_of         = CURRENT_DATE,
                 updated_at        = now()
           WHERE subscriber_id = NEW.subscriber_id;
          PERFORM public._resync_bucket_units(NEW.subscriber_id);

          -- Internal, non-recursive marker row. amount = -target (NEGATIVE).
          -- type='premium_sweep' matches neither trigger's WHEN clause.
          INSERT INTO public.transactions
            (id, subscriber_id, type, amount, date, status, method, txn_ref, source)
          VALUES ('tx-' || NEW.subscriber_id || '-sweep-' || replace(gen_random_uuid()::text, '-', ''),
                  NEW.subscriber_id, 'premium_sweep', -v_target, now(), 'settled',
                  'internal', 'SW-' || lpad(floor(random() * 900000 + 100000)::text, 6, '0'), 'own');

          -- Activate the building policies (BOTH tables) + reset accrued/target.
          UPDATE public.insurance_policies
             SET status = 'active', policy_start = now()::date, renewal_date = (now() + INTERVAL '1 year')::date
           WHERE subscriber_id = NEW.subscriber_id AND funded_by = 'self' AND status = 'building';
          UPDATE public.subscriber_insurance_products
             SET status = 'active', policy_start = now()::date, renewal_date = (now() + INTERVAL '1 year')::date, updated_at = now()
           WHERE subscriber_id = NEW.subscriber_id AND funded_by = 'self' AND status = 'building';

          UPDATE public.contribution_schedules
             SET insurance_premium_target = 0, insurance_premium_accrued = 0, updated_at = now()
           WHERE subscriber_id = NEW.subscriber_id;
        ELSE
          -- Not yet — persist the accrual + the refreshed target.
          UPDATE public.contribution_schedules
             SET insurance_premium_accrued = v_new_accrued, insurance_premium_target = v_target, updated_at = now()
           WHERE subscriber_id = NEW.subscriber_id;
        END IF;
      END IF;
    END IF;

    -- [rev] LAZY INDEXATION (independent of insurance): bump the schedule amount
    -- once per anniversary year. Same no-pg_cron pattern. v_sched is the pre-
    -- update snapshot, so the pct/marker read here are the original values.
    IF v_sched.contribution_indexation_pct > 0
       AND (v_sched.last_indexed_at IS NULL OR now() >= v_sched.last_indexed_at + INTERVAL '1 year') THEN
      UPDATE public.contribution_schedules
         SET amount = ROUND(amount * (1 + contribution_indexation_pct / 100.0)),
             last_indexed_at = now(), updated_at = now()
       WHERE subscriber_id = NEW.subscriber_id;
    END IF;
  END IF;
  -- ── end 0072 block ────────────────────────────────────────────────────────

  -- (c) First-contribution commission ----------------------------------------
  SELECT s.agent_id, s.name, a.branch_id
    INTO v_agent_id, v_subscriber_name, v_branch_id
    FROM public.subscribers s
    LEFT JOIN public.agents a ON a.id = s.agent_id
   WHERE s.id = NEW.subscriber_id;

  IF v_agent_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.commissions
       WHERE subscriber_id = NEW.subscriber_id
         AND agent_id = v_agent_id
    ) THEN
      -- 0089: the rate is per-DISTRIBUTOR now. `v_branch_id` is already
      -- resolved above, and the helper walks branch -> distributor -> its rate,
      -- falling back to the platform `id='default'` row. A NULL result still
      -- means "generate no commission", exactly as before.
      v_commission_rate := public.commission_rate_for_branch(v_branch_id);

      IF v_commission_rate IS NOT NULL THEN
        v_new_commission_id := 'c-' || lpad(
          nextval('public.commission_id_seq')::text, 8, '0'
        );

        INSERT INTO public.commissions (
          id,
          agent_id,
          branch_id,
          subscriber_id,
          subscriber_name,
          amount,
          status,
          first_contribution_date,
          due_date
        ) VALUES (
          v_new_commission_id,
          v_agent_id,
          v_branch_id,
          NEW.subscriber_id,
          v_subscriber_name,
          v_commission_rate,
          'due',
          NEW.date::date,
          NEW.date::date
        );
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$function$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) request_withdrawal — redeems at the register price
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.request_withdrawal(p_nonce text, p_amount numeric, p_bucket text DEFAULT NULL::text, p_reason text DEFAULT NULL::text, p_method text DEFAULT 'MTN Mobile Money'::text, p_split_retirement numeric DEFAULT NULL::numeric, p_split_emergency numeric DEFAULT NULL::numeric)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_role          text := (SELECT auth.jwt()) ->> 'app_role';
  v_subscriber_id text := (SELECT auth.jwt()) ->> 'subscriberId';
  v_total_balance numeric;
  v_unit_price    numeric;                    -- 0104: the fund NAV in force today
  v_split_ret     numeric := p_split_retirement;
  v_split_emg     numeric := p_split_emergency;
  v_ref           text;
  v_tx_id         text;
  v_wd_id         text;
  v_bucket        text;
  v_prior         jsonb;
  v_result        jsonb;
BEGIN
  IF v_role IS DISTINCT FROM 'subscriber' THEN
    RAISE EXCEPTION 'role % cannot request a withdrawal', v_role USING ERRCODE = 'P0001';
  END IF;
  IF v_subscriber_id IS NULL OR v_subscriber_id = '' THEN
    RAISE EXCEPTION 'missing subscriberId claim' USING ERRCODE = 'P0001';
  END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'amount must be positive' USING ERRCODE = 'P0001';
  END IF;

  -- 0104: redeem at the fund NAV, not a hardcoded 1,000.
  v_unit_price := public.latest_nav();

  -- Idempotency short-circuit: a replay of the same nonce returns the prior
  -- withdrawal row without re-debiting the balance.
  IF p_nonce IS NOT NULL AND p_nonce <> '' THEN
    SELECT result INTO v_prior FROM public.money_nonces WHERE nonce = p_nonce;
    IF v_prior IS NOT NULL THEN
      RETURN v_prior;
    END IF;
  END IF;

  -- F-5: server-side "withdraw ≤ available balance" guard. Lock the balance row
  -- so a concurrent withdrawal can't over-draw past the check.
  SELECT total_balance INTO v_total_balance
    FROM public.subscriber_balances
   WHERE subscriber_id = v_subscriber_id
   FOR UPDATE;
  v_total_balance := COALESCE(v_total_balance, 0);

  IF p_amount > v_total_balance THEN
    RAISE EXCEPTION 'withdrawal of % exceeds available balance %', p_amount, v_total_balance
      USING ERRCODE = 'P0001';
  END IF;

  -- Resolve the split: explicit splits win; else a bucket routes the whole
  -- amount; else NULL (the trigger falls back to emergency-first). Mirrors the
  -- prior JS requestWithdrawal resolution.
  IF v_split_ret IS NULL AND v_split_emg IS NULL AND p_bucket IS NOT NULL THEN
    IF p_bucket = 'retirement' THEN
      v_split_ret := p_amount; v_split_emg := 0;
    ELSE
      v_split_ret := 0; v_split_emg := p_amount;
    END IF;
  END IF;

  -- F-5 (cont.): if both splits are supplied, they must sum to the amount so the
  -- per-bucket debits can't desync from the total (the trigger debits total by
  -- ABS(amount) but buckets by their own splits).
  IF v_split_ret IS NOT NULL AND v_split_emg IS NOT NULL
     AND (v_split_ret + v_split_emg) <> p_amount THEN
    RAISE EXCEPTION 'split_retirement + split_emergency (%) must equal amount %',
      v_split_ret + v_split_emg, p_amount USING ERRCODE = 'P0001';
  END IF;

  v_bucket := COALESCE(p_bucket, 'emergency');
  v_ref    := 'WD-' || lpad(floor(random() * 900000 + 100000)::text, 6, '0');
  v_tx_id  := 'tx-' || v_subscriber_id || '-wd-' || replace(gen_random_uuid()::text, '-', '');
  v_wd_id  := 'wd-' || v_subscriber_id || '-'    || replace(gen_random_uuid()::text, '-', '');

  -- 1. Ledger row → AFTER INSERT trigger debits subscriber_balances buckets.
  INSERT INTO public.transactions (
    id, subscriber_id, type, amount, date, status, method,
    txn_ref, bucket, split_retirement, split_emergency, source
  ) VALUES (
    v_tx_id, v_subscriber_id, 'withdrawal', p_amount, now(), 'processing', p_method,
    v_ref, p_bucket, v_split_ret, v_split_emg, 'own'
  );

  -- F-3: decrement units, which the withdrawal trigger still never touches, so
  -- units × NAV ≈ total_balance holds after a runtime withdrawal. Floor at 0.
  -- 0104: redeem units at the NAV and drop the SAME FRACTION of cost basis
  -- (average-cost). Because the fraction of units removed equals the fraction
  -- of basis removed, growth% is INVARIANT to withdrawals — reducing basis by
  -- simple net cash-in instead yields -233% outliers for heavy withdrawers.
  -- Every SET right-hand side reads the PRE-UPDATE row, so `units` below is
  -- the holding before this redemption.
  UPDATE public.subscriber_balances
     SET units      = GREATEST(0, units - LEAST(p_amount / v_unit_price, units)),
         invested   = CASE WHEN units > 0
                        THEN GREATEST(0, invested * (1 - LEAST(p_amount / v_unit_price, units) / units))
                        ELSE 0 END,
         nav_as_of  = CURRENT_DATE,
         updated_at = now()
   WHERE subscriber_id = v_subscriber_id;

  -- 0072 [H3]: clawback accrued so a withdrawal can't strand accrued >= target
  -- while emergency_balance < target (which would let the next contribution
  -- sweep money that is no longer in the bucket). Clamp accrued to what remains
  -- in the emergency bucket AFTER this withdrawal debited it above.
  UPDATE public.contribution_schedules
     SET insurance_premium_accrued = LEAST(
           insurance_premium_accrued,
           GREATEST(0, (SELECT emergency_balance FROM public.subscriber_balances
                          WHERE subscriber_id = v_subscriber_id))),
         updated_at = now()
   WHERE subscriber_id = v_subscriber_id
     AND insurance_funding_mode = 'save_to_cover';

  -- 0104: re-derive bucket units from the bucket balances the withdrawal
  -- trigger has just debited. Deliberately NOT split from v_split_ret/v_split_emg
  -- — both are NULL in the common case and this function does not implement the
  -- trigger's emergency-first fallback, so deriving is the only way the two
  -- cannot drift.
  PERFORM public._resync_bucket_units(v_subscriber_id);

  -- 2. History row → the WithdrawalsHistory report consumes this (same txn).
  INSERT INTO public.withdrawals (
    id, subscriber_id, amount, bucket, reason, method, status, date, reference
  ) VALUES (
    v_wd_id, v_subscriber_id, p_amount, v_bucket, p_reason, p_method, 'processing',
    (now())::date, v_ref
  );

  -- Return shape matches mapWithdrawalRow's camelCase contract (the legacy
  -- requestWithdrawal return object).
  v_result := jsonb_build_object(
    'id',        v_wd_id,
    'amount',    p_amount,
    'bucket',    v_bucket,
    'reason',    p_reason,
    'method',    p_method,
    'status',    'processing',
    'date',      to_char(now(), 'YYYY-MM-DD'),
    'reference', v_ref
  );

  IF p_nonce IS NOT NULL AND p_nonce <> '' THEN
    INSERT INTO public.money_nonces (nonce, subscriber_id, kind, result)
    VALUES (p_nonce, v_subscriber_id, 'withdrawal', v_result)
    ON CONFLICT (nonce) DO NOTHING;
  END IF;

  RETURN v_result;
END;
$function$;

-- The signature is unchanged, so 0072's grants survive CREATE OR REPLACE.
-- Re-asserted anyway: a lost REVOKE here would expose a money mover to anon.
REVOKE ALL ON FUNCTION public.request_withdrawal(text, numeric, text, text, text, numeric, numeric)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.request_withdrawal(text, numeric, text, text, text, numeric, numeric)
  TO authenticated;


-- ─────────────────────────────────────────────────────────────────────────────
-- 3) publish_nav_snapshot — the admin's write path, and the ONLY one
-- ─────────────────────────────────────────────────────────────────────────────
-- nav_snapshots has no write policy by design; this DEFINER function is how a
-- price gets published. It is atomic: the register row and the revaluation of
-- every member land in one transaction, so the book can never be half-priced.
CREATE OR REPLACE FUNCTION public.publish_nav_snapshot(
  p_nav_date     DATE,
  p_unit_price   NUMERIC,
  p_fund_code    TEXT    DEFAULT 'UPU-BAL',
  p_source       TEXT    DEFAULT 'admin_manual',
  p_confirm_move BOOLEAN DEFAULT FALSE
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_role       TEXT := (SELECT auth.jwt()) ->> 'app_role';
  v_actor      TEXT := COALESCE((SELECT auth.jwt()) ->> 'name', 'admin');
  v_prev_price NUMERIC;
  v_prev_date  DATE;
  v_move       NUMERIC := NULL;
  v_newest     DATE;
  v_is_newest  BOOLEAN;
  v_id         TEXT;
  v_units      NUMERIC;
  v_aum        NUMERIC;
  v_members    INTEGER;
BEGIN
  IF v_role IS DISTINCT FROM 'admin' THEN
    RAISE EXCEPTION 'role % cannot publish a unit price', v_role USING ERRCODE = 'P0001';
  END IF;
  IF p_unit_price IS NULL OR p_unit_price <= 0 THEN
    RAISE EXCEPTION 'unit price must be greater than zero' USING ERRCODE = 'P0001';
  END IF;
  IF p_nav_date IS NULL OR p_nav_date > CURRENT_DATE THEN
    RAISE EXCEPTION 'cannot publish a price for a future date' USING ERRCODE = 'P0001';
  END IF;

  -- Serialise concurrent publishes on this fund so two admins cannot interleave
  -- a revaluation between each other's register write.
  PERFORM 1 FROM public.nav_snapshots
   WHERE fund_code = p_fund_code FOR UPDATE;

  SELECT unit_price, nav_date INTO v_prev_price, v_prev_date
    FROM public.nav_snapshots
   WHERE fund_code = p_fund_code AND status = 'published' AND nav_date < p_nav_date
   ORDER BY nav_date DESC LIMIT 1;

  IF v_prev_price IS NOT NULL AND v_prev_price > 0 THEN
    v_move := round(((p_unit_price - v_prev_price) / v_prev_price) * 100, 4);
    -- Server-side guard-rail. The client confirm dialog is a courtesy; THIS is
    -- the gate, so a scripted or replayed call cannot skip it.
    IF abs(v_move) > 10 AND NOT p_confirm_move THEN
      RAISE EXCEPTION
        'price move of %%% from % on % needs confirmation',
        round(v_move, 2), v_prev_price, v_prev_date
        USING ERRCODE = 'P0001';
    END IF;
  END IF;

  -- Re-publishing a day CORRECTS it, and flips a 'pending' day to 'published' —
  -- which is exactly how the admin clears a "Delayed NAV updation" signal.
  INSERT INTO public.nav_snapshots
    (fund_code, nav_date, unit_price, status, published_at, source, published_by)
  VALUES
    (p_fund_code, p_nav_date, p_unit_price, 'published', now(), p_source, v_actor)
  ON CONFLICT (fund_code, nav_date) DO UPDATE SET
    unit_price   = EXCLUDED.unit_price,
    status       = 'published',
    published_at = now(),
    source       = EXCLUDED.source,
    published_by = EXCLUDED.published_by
  RETURNING id INTO v_id;

  -- Revalue ONLY when this is now the newest published day. A back-dated
  -- correction must not restate today's book at a stale price.
  SELECT max(nav_date) INTO v_newest
    FROM public.nav_snapshots
   WHERE fund_code = p_fund_code AND status = 'published';
  v_is_newest := (v_newest = p_nav_date);

  IF v_is_newest AND p_fund_code = 'UPU-BAL' THEN
    -- Complement rule: round the total and the retirement leg, then take
    -- emergency as the difference. Rounding all three independently is what
    -- would trip v_reconciliation_exceptions.split_mismatch across 5,060 rows.
    UPDATE public.subscriber_balances
       SET total_balance      = round(units * p_unit_price),
           retirement_balance = round(retirement_units * p_unit_price),
           emergency_balance  = round(units * p_unit_price)
                                - round(retirement_units * p_unit_price),
           nav_as_of          = p_nav_date,
           updated_at         = now();

    -- 0072 [H3] parity: a NAV fall can push emergency_balance below an already
    -- accrued save-to-cover target, which would let the next contribution sweep
    -- money that is no longer in the bucket. Same clamp request_withdrawal does.
    UPDATE public.contribution_schedules s
       SET insurance_premium_accrued = LEAST(
             s.insurance_premium_accrued,
             GREATEST(0, (SELECT b.emergency_balance FROM public.subscriber_balances b
                           WHERE b.subscriber_id = s.subscriber_id))),
           updated_at = now()
     WHERE s.insurance_funding_mode = 'save_to_cover';

    -- Denormalised per-member copy of the fund price. Permitted because the
    -- editable-columns trigger returns early for a non-'subscriber' role.
    UPDATE public.subscribers
       SET current_unit_value = p_unit_price,
           unit_value_as_of   = now();
  END IF;

  SELECT COALESCE(sum(units), 0), COALESCE(sum(total_balance), 0), count(*)
    INTO v_units, v_aum, v_members
    FROM public.subscriber_balances;

  UPDATE public.nav_snapshots
     SET units_in_issue = v_units, aum = v_aum, members_priced = v_members
   WHERE id = v_id;

  RETURN jsonb_build_object(
    'id',                v_id,
    'fundCode',          p_fund_code,
    'navDate',           to_char(p_nav_date, 'YYYY-MM-DD'),
    'unitPrice',         p_unit_price,
    'previousUnitPrice', v_prev_price,
    'previousNavDate',   to_char(v_prev_date, 'YYYY-MM-DD'),
    'changePct',         v_move,
    'revalued',          v_is_newest,
    'unitsInIssue',      v_units,
    'aum',               v_aum,
    'membersPriced',     v_members
  );
END;
$function$;

REVOKE ALL    ON FUNCTION public.publish_nav_snapshot(DATE, NUMERIC, TEXT, TEXT, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.publish_nav_snapshot(DATE, NUMERIC, TEXT, TEXT, BOOLEAN) TO authenticated;


-- ─────────────────────────────────────────────────────────────────────────────
-- 4) get_nav_overview — everything the NAV page's header needs, in one call
-- ─────────────────────────────────────────────────────────────────────────────
-- `series` is returned INLINE so the trend chart needs no second round-trip.
-- pendingDays is computed HERE from nav_snapshots rather than read from
-- get_admin_attention, so the page works whether or not 0097 is applied.
CREATE OR REPLACE FUNCTION public.get_nav_overview(
  p_fund_code TEXT DEFAULT 'UPU-BAL'
) RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_role   TEXT := (SELECT auth.jwt()) ->> 'app_role';
  v_cur    RECORD;
  v_prev   RECORD;
  v_result JSONB;
BEGIN
  IF v_role IS DISTINCT FROM 'admin' THEN
    RAISE EXCEPTION 'role % cannot read the NAV overview', v_role USING ERRCODE = 'P0001';
  END IF;

  SELECT unit_price, nav_date INTO v_cur
    FROM public.nav_snapshots
   WHERE fund_code = p_fund_code AND status = 'published'
   ORDER BY nav_date DESC LIMIT 1;

  SELECT unit_price, nav_date INTO v_prev
    FROM public.nav_snapshots
   WHERE fund_code = p_fund_code AND status = 'published'
     AND nav_date < COALESCE(v_cur.nav_date, CURRENT_DATE)
   ORDER BY nav_date DESC LIMIT 1;

  SELECT jsonb_build_object(
    'fundCode',       p_fund_code,
    'currentNav',     v_cur.unit_price,
    'currentNavDate', to_char(v_cur.nav_date, 'YYYY-MM-DD'),
    'previousNav',    v_prev.unit_price,
    'previousNavDate',to_char(v_prev.nav_date, 'YYYY-MM-DD'),
    'changeAbs',      CASE WHEN v_prev.unit_price IS NOT NULL
                        THEN round(v_cur.unit_price - v_prev.unit_price, 2) END,
    'changePct',      CASE WHEN COALESCE(v_prev.unit_price, 0) > 0
                        THEN round(((v_cur.unit_price - v_prev.unit_price) / v_prev.unit_price) * 100, 2) END,
    'unitsInIssue',   b.units,
    'aum',            b.aum,
    'totalInvested',  b.invested,
    'totalGrowth',    b.aum - b.invested,
    'growthPct',      CASE WHEN b.invested > 0
                        THEN round(((b.aum - b.invested) / b.invested) * 100, 2) ELSE 0 END,
    'membersPriced',  b.priced,
    'membersUnpriced',b.unpriced,
    'firstNavDate',   to_char(r.first_date, 'YYYY-MM-DD'),
    'publishedCount', r.published_count,
    'pendingDays',    r.pending_days,
    'lastPublishedDaysAgo', CURRENT_DATE - v_cur.nav_date,
    'series',         COALESCE(s.series, '[]'::jsonb)
  ) INTO v_result
  FROM (
    SELECT COALESCE(sum(units), 0)         AS units,
           COALESCE(sum(total_balance), 0) AS aum,
           COALESCE(sum(invested), 0)      AS invested,
           count(*) FILTER (WHERE nav_as_of IS NOT NULL) AS priced,
           count(*) FILTER (WHERE nav_as_of IS NULL)     AS unpriced
      FROM public.subscriber_balances
  ) b,
  (
    SELECT min(nav_date) FILTER (WHERE status = 'published')                       AS first_date,
           count(*)      FILTER (WHERE status = 'published')                       AS published_count,
           count(*)      FILTER (WHERE status = 'pending' AND nav_date < CURRENT_DATE) AS pending_days
      FROM public.nav_snapshots WHERE fund_code = p_fund_code
  ) r,
  (
    SELECT jsonb_agg(jsonb_build_object(
             'date',      to_char(q.nav_date, 'YYYY-MM-DD'),
             'unitPrice', q.unit_price,
             'aum',       q.aum) ORDER BY q.nav_date) AS series
      FROM (
        SELECT nav_date, unit_price, aum
          FROM public.nav_snapshots
         WHERE fund_code = p_fund_code AND status = 'published'
         ORDER BY nav_date DESC LIMIT 260
      ) q
  ) s;

  RETURN v_result;
END;
$function$;

REVOKE ALL    ON FUNCTION public.get_nav_overview(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_nav_overview(TEXT) TO authenticated;


-- ─────────────────────────────────────────────────────────────────────────────
-- 5) list_nav_snapshots — the paged history table
-- ─────────────────────────────────────────────────────────────────────────────
-- changePct is computed server-side with lag() so the client never re-sorts to
-- work out a day-on-day move.
CREATE OR REPLACE FUNCTION public.list_nav_snapshots(
  p_fund_code TEXT    DEFAULT 'UPU-BAL',
  p_limit     INTEGER DEFAULT 60,
  p_offset    INTEGER DEFAULT 0,
  p_status    TEXT    DEFAULT NULL
) RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
  v_role  TEXT := (SELECT auth.jwt()) ->> 'app_role';
  v_rows  JSONB;
  v_total INTEGER;
BEGIN
  IF v_role IS DISTINCT FROM 'admin' THEN
    RAISE EXCEPTION 'role % cannot read the NAV register', v_role USING ERRCODE = 'P0001';
  END IF;

  SELECT count(*) INTO v_total
    FROM public.nav_snapshots
   WHERE fund_code = p_fund_code
     AND (p_status IS NULL OR status = p_status);

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'id',                q.id,
           'navDate',           to_char(q.nav_date, 'YYYY-MM-DD'),
           'unitPrice',         q.unit_price,
           'previousUnitPrice', q.prev_price,
           'changePct',         CASE WHEN COALESCE(q.prev_price, 0) > 0
                                  THEN round(((q.unit_price - q.prev_price) / q.prev_price) * 100, 2) END,
           'status',            q.status,
           'publishedAt',       q.published_at,
           'publishedBy',       q.published_by,
           'source',            q.source,
           'unitsInIssue',      q.units_in_issue,
           'aum',               q.aum
         ) ORDER BY q.nav_date DESC), '[]'::jsonb) INTO v_rows
    FROM (
      SELECT *, lag(unit_price) OVER (ORDER BY nav_date) AS prev_price
        FROM public.nav_snapshots
       WHERE fund_code = p_fund_code
         AND (p_status IS NULL OR status = p_status)
       ORDER BY nav_date DESC
       LIMIT p_limit OFFSET p_offset
    ) q;

  RETURN jsonb_build_object('rows', v_rows, 'total', v_total);
END;
$function$;

REVOKE ALL    ON FUNCTION public.list_nav_snapshots(TEXT, INTEGER, INTEGER, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.list_nav_snapshots(TEXT, INTEGER, INTEGER, TEXT) TO authenticated;

COMMIT;
